# ============================
# Identidad del proyecto
# ============================
sonar.projectKey=runny_u
sonar.projectName=RUNNY_U
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

# ============================
# Código fuente
# ============================
# Incluye frontend (Angular) y backend (NestJS)
sonar.sources=runny_u-app/src,runny_u-back/src

# ============================
# Tests (dentro de cada proyecto)
# ============================
sonar.tests=runny_u-app/src,runny_u-back/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.js,**/*.test.js,**/*.module.ts

# ============================
# Exclusiones
# ============================
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.angular/**,**/.vite/**,**/coverage/**

# ============================
# Reportes de cobertura
# ============================
# Backend (NestJS -> npm run test:cov)
# Frontend (Angular -> ng test --code-coverage --karma-config karma.conf.js)
sonar.javascript.lcov.reportPaths=runny_u-back/coverage/lcov.info,runny_u-app/coverage/runny_u-app/lcov.info

